### ISSUE TITLE
access_denied on request to /oauth/identity

### ISSUE THREAD

**Issue by ochorocho** [fgtclb/typo3-oauth2-server#2]
When i try to get the resource owner i get `access_denied` on my client:
 
```php
        $this->providerOptions = [
             'clientId'       => 'XXXXXX',
             'clientSecret'   => 'XXXXXXX',
             'redirectUri'    => 'https://simple-oauth2-client-example.ddev.site/auth.php',
             'urlAuthorize'   => 'https://www.domain.de/oauth/authorize',
             'urlAccessToken' => 'https://www.domain.de/oauth/token',
             'urlResourceOwnerDetails' => 'https://www.domain.de/oauth/identity',
        ];
```

```php
    public function getResourceIdentity() {
        $accessToken = $this->provider->getAccessToken('authorization_code', [
            'code' => $_GET['code']
        ]);

        return $this->provider->getResourceOwner($accessToken);
    }
```

Error:
```
Fatal error: Uncaught League\OAuth2\Client\Provider\Exception\IdentityProviderException: access_denied in /var/www/html/vendor/league/oauth2-client/src/Provider/GenericProvider.php:216 Stack trace: #0 /var/www/html/vendor/league/oauth2-client/src/Provider/AbstractProvider.php(645): League\OAuth2\Client\Provider\GenericProvider->checkResponse(Object(GuzzleHttp\Psr7\Response), Array) #1 /var/www/html/vendor/league/oauth2-client/src/Provider/AbstractProvider.php(794): League\OAuth2\Client\Provider\AbstractProvider->getResponse(Object(GuzzleHttp\Psr7\Request)) #2 /var/www/html/vendor/league/oauth2-client/src/Provider/AbstractProvider.php(777): League\OAuth2\Client\Provider\AbstractProvider->fetchResourceOwnerDetails(Object(League\OAuth2\Client\Token\AccessToken)) #3 /var/www/html/app/AuthCodeHandler.php(125): League\OAuth2\Client\Provider\AbstractProvider->getResourceOwner(Object(League\OAuth2\Client\Token\AccessToken)) #4 /var/www/html/auth.php(60): App\AuthCodeHandler->getResourceIdentity() #5 {main} thrown in /var/www/html/vendor/league/oauth2-client/src/Provider/GenericProvider.php on line 216
```

Not sure if this is a problem with my code or the Server.
Tokens look fine.

**Comment by ochorocho** [comment]
Adding this to `.htaccess` fixed the issue.

```
RewriteEngine On
RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]
```
