### ISSUE TITLE
"The requested page does not exist" when trying to get "identity"

### ISSUE THREAD

**Issue by ochorocho** [fgtclb/typo3-oauth2-server#3]
Hey, 

when trying to get the users identity by sending a GET request to https://domain.ddev.site/oauth/identity `The requested page does not exist` is returned.

Log:

```
Mon, 24 Aug 2020 14:39:17 +0000 [CRITICAL] request="e7e7a7593c6d7" component="TYPO3.CMS.Core.Error.DebugExceptionHandler": Core: Exception handler (WEB): Uncaught TYPO3 Exception: #1518472189: The requested page does not exist | TYPO3\CMS\Core\Error\Http\PageNotFoundException thrown in file /var/www/html/public/typo3/sysext/frontend/Classes/Controller/ErrorController.php in line 80. Requested URL: https://domain.ddev.site/oauth/identity - {"TYPO3_MODE":"FE","exception":"TYPO3\\CMS\\Core\\Error\\Http\\PageNotFoundException: The requested page does not exist in /var/www/html/public/typo3/sysext/frontend/Classes/Controller/ErrorController.php:80\nStack trace:\n#0 /var/www/html/public/typo3/sysext/frontend/Classes/Middleware/PageResolver.php(116): TYPO3\\CMS\\Frontend\\Controller\\ErrorController->pageNotFoundAction(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), 'The requested p...', Array)\n#1 /var/www/html/public/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(138): TYPO3\\CMS\\Frontend\\Middleware\\PageResolver->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(class@anonymous))\n#2 /var/www/html/public/typo3/sysext/frontend/Classes/Middleware/PreviewSimulator.php(62): class@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#3 /var/www/html/public/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(138): TYPO3\\CMS\\Frontend\\Middleware\\PreviewSimulator->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(class@anonymous))\n#4 /var/www/html/public/typo3/sysext/redirects/Classes/Http/Middleware/RedirectHandler.php(70): class@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#5 /var/www/html/public/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(138): TYPO3\\CMS\\Redirects\\Http\\Middleware\\RedirectHandler->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(class@anonymous))\n#6 /var/www/html/public/typo3/sysext/adminpanel/Classes/Middleware/AdminPanelInitiator.php(58): class@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#7 /var/www/html/public/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(138): TYPO3\\CMS\\Adminpanel\\Middleware\\AdminPanelInitiator->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(class@anonymous))\n#8 /var/www/html/public/typo3/sysext/frontend/Classes/Middleware/StaticRouteResolver.php(62): class@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#9 /var/www/html/public/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(138): TYPO3\\CMS\\Frontend\\Middleware\\StaticRouteResolver->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(class@anonymous))\n#10 /var/www/html/public/typo3/sysext/frontend/Classes/Middleware/SiteBaseRedirectResolver.php(86): class@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#11 /var/www/html/public/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(138): TYPO3\\CMS\\Frontend\\Middleware\\SiteBaseRedirectResolver->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(class@anonymous))\n#12 /var/www/html/public/typo3conf/ext/oauth2_server/Classes/Middleware/OAuth2AccessToken.php(26): class@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#13 /var/www/html/public/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(138): FGTCLB\\OAuth2Server\\Middleware\\OAuth2AccessToken->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(class@anonymous))\n#14 /var/www/html/public/typo3conf/ext/oauth2_server/Classes/Middleware/OAuth2Identity.php(36): class@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#15 /var/www/html/public/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(138): FGTCLB\\OAuth2Server\\Middleware\\OAuth2Identity->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(class@anonymous))\n#16 /var/www/html/public/typo3conf/ext/oauth2_server/Classes/Middleware/OAuth2Authorization.php(53): class@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#17 /var/www/html/public/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(138): FGTCLB\\OAuth2Server\\Middleware\\OAuth2Authorization->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(class@anonymous))\n#18 /var/www/html/public/typo3/sysext/frontend/Classes/Middleware/MaintenanceMode.php(53): class@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#19 /var/www/html/public/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(138): TYPO3\\CMS\\Frontend\\Middleware\\MaintenanceMode->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(class@anonymous))\n#20 /var/www/html/public/typo3/sysext/frontend/Classes/Middleware/SiteResolver.php(68): class@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#21 /var/www/html/public/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(138): TYPO3\\CMS\\Frontend\\Middleware\\SiteResolver->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(class@anonymous))\n#22 /var/www/html/public/typo3/sysext/adminpanel/Classes/Middleware/SqlLogging.php(49): class@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#23 /var/www/html/public/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(138): TYPO3\\CMS\\Adminpanel\\Middleware\\SqlLogging->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(class@anonymous))\n#24 /var/www/html/public/typo3/sysext/frontend/Classes/Middleware/BackendUserAuthenticator.php(95): class@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#25 /var/www/html/public/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(138): TYPO3\\CMS\\Frontend\\Middleware\\BackendUserAuthenticator->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(class@anonymous))\n#26 /var/www/html/public/typo3/sysext/frontend/Classes/Middleware/FrontendUserAuthenticator.php(79): class@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#27 /var/www/html/public/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(138): TYPO3\\CMS\\Frontend\\Middleware\\FrontendUserAuthenticator->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(class@anonymous))\n#28 /var/www/html/public/typo3/sysext/frontend/Classes/Middleware/TypoScriptFrontendInitialization.php(90): class@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#29 /var/www/html/public/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(138): TYPO3\\CMS\\Frontend\\Middleware\\TypoScriptFrontendInitialization->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(class@anonymous))\n#30 /var/www/html/public/typo3/sysext/frontend/Classes/Middleware/EidHandler.php(50): class@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#31 /var/www/html/public/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(138): TYPO3\\CMS\\Frontend\\Middleware\\EidHandler->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(class@anonymous))\n#32 /var/www/html/public/typo3/sysext/frontend/Classes/Middleware/PreprocessRequestHook.php(57): class@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#33 /var/www/html/public/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(138): TYPO3\\CMS\\Frontend\\Middleware\\PreprocessRequestHook->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(class@anonymous))\n#34 /var/www/html/public/typo3/sysext/core/Classes/Middleware/NormalizedParamsAttribute.php(58): class@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#35 /var/www/html/public/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(138): TYPO3\\CMS\\Core\\Middleware\\NormalizedParamsAttribute->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(class@anonymous))\n#36 /var/www/html/public/typo3/sysext/frontend/Classes/Middleware/TimeTrackerInitialization.php(49): class@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#37 /var/www/html/public/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(138): TYPO3\\CMS\\Frontend\\Middleware\\TimeTrackerInitialization->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(class@anonymous))\n#38 /var/www/html/public/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(67): class@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#39 /var/www/html/public/typo3/sysext/core/Classes/Http/AbstractApplication.php(108): TYPO3\\CMS\\Core\\Http\\MiddlewareDispatcher->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#40 /var/www/html/public/typo3/sysext/frontend/Classes/Http/Application.php(69): TYPO3\\CMS\\Core\\Http\\AbstractApplication->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#41 /var/www/html/public/typo3/sysext/core/Classes/Http/AbstractApplication.php(120): TYPO3\\CMS\\Frontend\\Http\\Application->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#42 /var/www/html/public/index.php(24): TYPO3\\CMS\\Core\\Http\\AbstractApplication->run()\n#43 /var/www/html/public/index.php(25): {closure}()\n#44 {main}"}
```

Any idea on how to fix this?

Thank you

**Comment by ochorocho** [comment]
Not sure of this is a problem of the middleware. Seems like the page is redirected before the the code was executed

**Comment by mbrodala** [comment]
What is the exact URI you have when this error occurs? It must be `https://example.org/oauth/identity`, otherwise the `OAuth2Identity` won't respond.

**Comment by ochorocho** [comment]
Xdebug shows the follwoing:
![grafik](https://user-images.githubusercontent.com/4623070/95553217-5feb2d00-0a0e-11eb-91b1-614c4ecaacb3.png)

This is my client code for testing:

```
<?php

require __DIR__ . '/vendor/autoload.php';

$provider = new \League\OAuth2\Client\Provider\GenericProvider([
    'clientId'                => 'XXX',    // The client ID assigned to you by the provider
    'clientSecret'            => 'XXXX',   // The client password assigned to you by the provider
    'redirectUri'             => 'https://oauth-client.ddev.site',
    'urlAuthorize'            => 'https://www.domain.de/oauth/authorize',
    'urlAccessToken'          => 'https://www.domain.de/oauth/token',
    'urlResourceOwnerDetails' => 'https://www.domain.de/oauth/identity'
]);

$guzzyClient = new GuzzleHttp\Client([
    \GuzzleHttp\RequestOptions::VERIFY => false,
]);

$provider->setHttpClient($guzzyClient);

if (!isset($_GET['code'])) {

    // Fetch the authorization URL from the provider; this returns the
    // urlAuthorize option and generates and applies any necessary parameters
    // (e.g. state).
    $authorizationUrl = $provider->getAuthorizationUrl();

    // Get the state generated for you and store it to the session.
    $_SESSION['oauth2state'] = $provider->getState();

    // Redirect the user to the authorization URL.
    header('Location: ' . $authorizationUrl);
    exit;

// Check given state against previously stored one to mitigate CSRF attack
} elseif (empty($_GET['state']) || (isset($_SESSION['oauth2state']) && $_GET['state'] !== $_SESSION['oauth2state'])) {

    if (isset($_SESSION['oauth2state'])) {
        unset($_SESSION['oauth2state']);
    }

    exit('Invalid state');

} else {

    try {

        // Try to get an access token using the authorization code grant.
        $accessToken = $provider->getAccessToken('authorization_code', [
            'code' => $_GET['code']
        ]);

        // We have an access token, which we may use in authenticated
        // requests against the service provider's API.
        echo '<h2>Access Token:</h2> ' . $accessToken->getToken() . "<br>";
        echo '<h2>Refresh Token:</h2> ' . $accessToken->getRefreshToken() . "<br>";
        echo '<h2>Expired in:</h2> ' . $accessToken->getExpires() . "<br>";
        echo '<h2>Already expired?</h2> ' . ($accessToken->hasExpired() ? 'expired' : 'not expired') . "<br>";

        echo "<hr>";
        echo "<h1>Token</h1>";
        echo "<pre>";
        print_r($accessToken);
        echo "</pre>";
        echo "<hr>";

        $resourceOwner = $provider->getResourceOwnerDetailsUrl($accessToken);
        $resourceOwner = $provider->getResourceOwner($accessToken);
        var_dump($resourceOwner);

    } catch (\League\OAuth2\Client\Provider\Exception\IdentityProviderException $e) {
        // Failed to get the access token or user details.
        exit($e->getMessage());
    }
}
```

**Comment by ochorocho** [comment]
For testing i have edited OAuth2Identity.php and the output `<h1>AHHHHH!!!!!!</h1>` ... so that confuses me even more.

```php
        if ($request->getUri()->getPath() === '/oauth/identity') {
            $factory = new ServerFactory();
            $server = $factory->buildResourceServer();

            echo "<h1>AHHHHH!!!!!!</h1>";
            try {
                $request = $server->validateAuthenticatedRequest($request);
                var_dump($request);
            } catch (OAuthServerException $e) {
                return $e->generateHttpResponse(new Response());
            }
        }
```

**Comment by mbrodala** [comment]
@ochorocho Sorry for leaving you hanging for such a long time. Currently this package itself does not do the final response for identity requests. It merely amends the request by adding `oauth_*` attributes after validating it.

So you need to add a custom middleware after out identity middleware which checks these attributes and returns a response. (See https://github.com/fgtclb/typo3-oauth2-server/commit/9560a392b13c13bf1ebe4302f372f999ba7336f8)

Without a middleware which returns a final response the remaining middlewares and request handler of TYPO3 will be processed which will obviously lead to 404 error. (Unless you add a page with a slug called `/oauth/identity` ;-) )

**Comment by ochorocho** [comment]
@mbrodala no worries. Thanks for your response. Now everything makes sense :-)

**Comment by mbrodala** [comment]
Alright, so I assume we can close this one? A generic middleware provided by default wouldn't make sense because the content of the final response depends on your usecase/client.

**Comment by ochorocho** [comment]
Yep :-)
